/* CBMC harness: nw_check itself, with the leaves abstracted.
 *
 * The blob is entirely nondeterministic, so this explores ALL inputs of this
 * length, not a sample. The leaves are replaced by stubs that assume only
 * what their own proofs establish -- so this run plus the three leaf runs is
 * one argument, and a post-condition asserted here that no leaf proof
 * delivers is a hole, not a result.
 *
 * The generated include is nwcheck.c with the leaf bodies removed. If a
 * body survived, the stub below would be a second definition and this would
 * not compile: that is the mechanism keeping "abstracted" honest. */
#include "nwcheck_comp.c"    /* generated by proofs/mkcomp.py */

#ifndef PROOF_UNITS
#define PROOF_UNITS 1u
#endif
#ifndef PROOF_BINDS
#define PROOF_BINDS 0u
#endif
#define LEN ((uint32_t)NW_BLOB_SIZE(PROOF_UNITS, PROOF_BINDS))

int nondet_int(void);
uint32_t nondet_u32(void);

/* --- the abstractions -------------------------------------------------
 *
 * Each returns an arbitrary answer, and when that answer is "accept" it
 * assumes ONLY what the matching leaf proof asserts. The two lists have to
 * stay in step; anything assumed here and not proven there is a hole.
 *
 *   name_ok      leaf_name_ok.c   -- non-empty, NUL-padded within the field
 *   path_ok_len  leaf_path_ok.c   -- absolute, NUL-terminated, no ".."
 *
 * hash_name, name_dup and the CRC are unconstrained. That is deliberate and
 * it is the stronger claim: nw_check must reach the same verdicts for ANY
 * hash, ANY duplicate judgement and ANY checksum. The CRC's own correctness
 * is a separate and easy obligation -- the suite's difftest against
 * zlib.crc32, which is what the baker uses. Invariant 8 already says the
 * checksum is diagnostic and the structural checks are the safety property;
 * proving those hold for an arbitrary checksum result is stronger than
 * proving them for one particular one. */
#ifdef PROOF_SIGCHECK
/* Signature-only build: gcc cannot parse __CPROVER_exists, and the point of
 * this build is the types, not the assumptions. See proofs/run.sh. */
#define PROOF_ASSUME_NUL(s, max) (void)0
#else
#define PROOF_ASSUME_NUL(s, max) \
    __CPROVER_assume(__CPROVER_exists { int i; i >= 0 && i < (max) \
                                        && (s)[i] == 0 })
#endif

static int name_ok(const char *s, int max)
{
    int r = nondet_int();
    if (r) {
        __CPROVER_assume(s[0] != 0);
        PROOF_ASSUME_NUL(s, max);
    }
    return r;
}

static int path_ok_len(const char *s, int max)
{
    int r = nondet_int();
    if (r) {
        __CPROVER_assume(s[0] == '/');
        PROOF_ASSUME_NUL(s, max);
    }
    return r;
}

static uint32_t hash_name(const char *s) { (void)s; return nondet_u32(); }

static int name_dup(struct nw_dup_tab *t, const struct nw_unit *u, uint32_t i)
{ (void)t; (void)u; (void)i; return nondet_int(); }

uint32_t nw_crc32_split(const void *a, uint32_t na, const void *b, uint32_t nb)
{ (void)a; (void)na; (void)b; (void)nb; return nondet_u32(); }

int main(void)
{
    static unsigned char blob[LEN];
    /* Every byte nondeterministic, without a fill loop. The loop version
     * forced the global unwind bound above the blob length, which multiplied
     * every real loop in nw_check and made the solver time out -- and worse,
     * the first run of it hit the bound and left the last 82 bytes concrete
     * zeros while reporting a failure that read like a nuisance. An
     * unwinding assertion is the tool saying the input space was silently
     * narrowed. docs/plans/02. */
    __CPROVER_havoc_object(blob);

    /* Pin the shape. SOUNDNESS ARGUMENT, because narrowing the input space
     * by accident is exactly what made that run worthless:
     *
     * nw_check computes need = NW_BLOB_SIZE(n_units, n_binds) and returns
     * NW_E_SIZE when len != need, BEFORE the unit loop and before anything
     * asserted below. At this LEN the only (n_units, n_binds) satisfying
     * that equation is the pair assumed here. So every input excluded
     * provably returns NW_E_SIZE and can never reach NW_OK, which is the
     * only branch under which anything is asserted. Nothing that could
     * falsify a post-condition is removed.
     *
     * Without it the unroller treats n_units as free and unwinds the unit
     * loop to the bound, multiplying the brick scan inside it -- 6,402
     * unwindings of that loop alone, measured. */
    {
        const struct nw_hdr *hh = nw_hdr(blob);
        __CPROVER_assume(hh->n_units == PROOF_UNITS);
        __CPROVER_assume(hh->n_binds == PROOF_BINDS);
    }

    int r = nw_check(blob, LEN);

#ifdef PROOF_VACUITY
    __CPROVER_assert(r != NW_OK, "VACUITY CONTROL: no blob is ever accepted");
#else
    /* If it says yes, these must hold. Each is something the runtime then
     * relies on without re-checking. */
    if (r == NW_OK) {
        const struct nw_unit *u = nw_units(blob);
        for (uint32_t k = 0; k < PROOF_UNITS; k++) {
            int nul = 0;
            for (int i = 0; i < NW_NAME_LEN; i++)
                if (u[k].name[i] == 0) nul = 1;
            __CPROVER_assert(nul, "accepted: unit name is NUL-terminated");
            __CPROVER_assert(u[k].exec_path[0] == '/',
                             "accepted: exec_path is absolute");
            __CPROVER_assert(u[k]._pad == 0, "accepted: spare byte is zero");
            __CPROVER_assert(u[k].brick[0] == 0 || (u[k].lids & NW_LID_NEWNS),
                             "accepted: a brick implies the NEWNS lid");
            __CPROVER_assert(!(u[k].lids & NW_LID_LANDLOCK) || u[k].brick[0],
                             "accepted: landlock implies a brick");
            __CPROVER_assert(u[k].kind == NW_KIND_ONESHOT
                             || u[k].kind == NW_KIND_LONGRUN,
                             "accepted: kind is one of the two");
            __CPROVER_assert(!(u[k].lids & ~(uint8_t)(NW_LID_SECCOMP
                                                      | NW_LID_LANDLOCK
                                                      | NW_LID_NEWNS
                                                      | NW_LID_NEWNET)),
                             "accepted: no lid bit outside the closed set");
        }
#if PROOF_BINDS > 0
        const struct nw_bind *bd = nw_binds(blob);
        for (uint32_t k = 0; k < PROOF_BINDS; k++) {
#ifdef PROOF_BIND_REACHED
            /* Reachability control. At PROOF_BINDS=0 this loop never runs,
             * so the two assertions below are reported SUCCESS while saying
             * nothing -- `__CPROVER_assert(0, ...)` passes there too, which
             * is how `claims` found it. This must FAIL, and it fails only
             * if the body is actually entered. Pairing an absence with the
             * positive that the mechanism ran, in a proof. */
            __CPROVER_assert(0, "REACHABILITY CONTROL: must fail");
#endif
            __CPROVER_assert(bd[k].unit < PROOF_UNITS,
                             "accepted: bind names a unit that exists");
            __CPROVER_assert(u[bd[k].unit].brick[0] != 0,
                             "accepted: a bind implies the unit has a brick");
        }
#endif
    }
#endif
    return 0;
}
