#!/usr/bin/env python3
"""Generate the compositional copy of nwcheck.c: the same translation unit
with the leaf function *bodies* removed, so a harness can supply stubs.

Generated, never edited. The first compositional harness kept a hand-copied
nwcheck.c beside it with the leaves turned into declarations -- a second copy
of a TCB file, maintained by memory, which is the defect this repository
names in three separate places. This script derives it instead, and fails
loudly if the shape it depends on is not there: a leaf that was renamed,
inlined or deleted stops the proof rather than silently proving the old copy.

A `static int f(...);` declaration with the definition supplied later in the
same translation unit is legal C, so the stubs stay file-local exactly as the
originals are.
"""
import re
import sys

# The leaves abstracted at the caller. Each must appear exactly once as a
# definition. Removing any name from this list means the caller proof runs
# against the real function, which is sound but usually too expensive -- that
# is the whole reason the composition exists.
LEAVES = ["name_ok", "path_ok_len", "hash_name", "name_dup", "nw_crc32_split"]


def strip_body(src, fn):
    """Replace fn's definition with a declaration; return (src, count)."""
    pat = re.compile(
        r"^([A-Za-z_][A-Za-z0-9_ \t\*]*\b" + re.escape(fn) + r"\s*\([^;{]*\))"
        r"\s*\n\{", re.M)
    hits = list(pat.finditer(src))
    if len(hits) != 1:
        return src, len(hits)
    m = hits[0]
    i = src.index("{", m.end() - 1)
    depth, j = 0, i
    while True:
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
        if j >= len(src):
            raise SystemExit(f"mkcomp: unbalanced braces in {fn}")
    return src[:m.start()] + m.group(1) + ";" + src[j + 1:], 1


def main():
    src = open(sys.argv[1]).read()
    for fn in LEAVES:
        src, n = strip_body(src, fn)
        if n != 1:
            raise SystemExit(
                f"mkcomp: expected exactly one definition of {fn}, found {n}."
                " nwcheck.c changed shape -- fix this script, do not proceed:"
                " a missed leaf is proven against its real body and a missed"
                " *caller* is proven against nothing.")
    # The bodies must actually be gone: a regex that matched and removed
    # nothing would leave a proof that looks composed and is not. Re-running
    # the matcher is the check, and it is not the only one -- if a body
    # survived here, the harness's stub would be a second definition of the
    # same function and the compile would fail.
    for fn in LEAVES:
        _, n = strip_body(src, fn)
        if n != 0:
            raise SystemExit(f"mkcomp: {fn}'s body survived stripping")
    out = open(sys.argv[2], "w")
    out.write("/* GENERATED by proofs/mkcomp.py from nwcheck.c -- do not"
              " edit. */\n")
    out.write(src)
    out.close()


if __name__ == "__main__":
    main()
