#!/usr/bin/env python3
"""Generate the spec files' limit constants from blob.h.

Invariant 3 says a limit is derived, never declared twice: NW_MAX_UNITS and
its friends must agree across blob.h, bakery/nw-cc.py, plan.als and
Plan.tla. For the two specs that agreement was maintained by hand, by
someone remembering -- and `drift` has reported the resulting mismatch more
than once.

This removes the class rather than checking for it. The numbers are read
out of blob.h and written into a generated Alloy module and a generated TLC
config, so the specs cannot hold a stale copy: there is no second
declaration left to drift.

Writes (both generated, both gitignored):
    specs/limits.als    -- opened by plan.als
    specs/Plan.cfg      -- the TLC config for Plan.tla

Not in the TCB. Run by tests/run.py before it invokes the solvers.
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The names the specs need, and what each is called in blob.h. Anything the
# specs reason about numerically belongs here; anything they do not, does
# not, because a constant nothing reads is a constant that rots.
WANTED = {
    "nwMaxUnits": "NW_MAX_UNITS",
    "nwMaxFds": "NW_MAX_FDS",
    "nwReserved": "NW_FD_RESERVED",
    "nwMaxBinds": "NW_MAX_BINDS",
}


def read_blob_h(path=None):
    src = open(path or os.path.join(ROOT, "blob.h")).read()
    out = {}
    for spec_name, c_name in WANTED.items():
        m = re.search(rf"^#define\s+{c_name}\s+(\d+)", src, re.M)
        if not m:
            raise SystemExit(
                f"gen-spec-limits: {c_name} not found in blob.h. The specs "
                f"derive their limits from it; a rename here is a four-place "
                f"change (invariant 3) and must not be papered over with a "
                f"default.")
        out[spec_name] = int(m.group(1))
    return out


def als(vals):
    body = "\n".join(
        f"fun {k}[]: Int {{ {v} }}" for k, v in sorted(vals.items()))
    return f"""/* GENERATED by tools/gen-spec-limits.py from blob.h. Do not edit.
   Regenerate rather than correcting this file: it exists so plan.als
   cannot hold a second, drifting copy of a limit (invariant 3). */
module limits

{body}
"""


def cfg(vals):
    return f"""\\* GENERATED by tools/gen-spec-limits.py from blob.h. Do not edit.
\\* Plan.tla's ASSUME compares these against the values it was written
\\* with; a blob.h change that Plan.tla has not followed fails the ASSUME,
\\* which is the drift invariant 3 exists to catch.
CONSTANTS
    MaxUnits = {vals['nwMaxUnits']}
    MaxFds = {vals['nwMaxFds']}
    Reserved = {vals['nwReserved']}
    MaxBinds = {vals['nwMaxBinds']}

INIT Init
NEXT Next

INVARIANTS
    FdBudgetCovers
"""


def generate(out_dir=None, blob_h=None):
    vals = read_blob_h(blob_h)
    d = out_dir or os.path.join(ROOT, "specs")
    os.makedirs(d, exist_ok=True)
    a, c = os.path.join(d, "limits.als"), os.path.join(d, "Plan.cfg")
    open(a, "w").write(als(vals))
    open(c, "w").write(cfg(vals))
    return vals, a, c


if __name__ == "__main__":
    v, a, c = generate()
    print(f"gen-spec-limits: {v}")
    print(f"  {a}")
    print(f"  {c}")
    sys.exit(0)
