#!/usr/bin/env python3
"""Generate the spec files' limit constants from blob.h.

Invariant 3 says a limit is derived, never declared twice: NW_MAX_UNITS and
its friends must agree across blob.h, bakery/nw-cc.py, plan.als and
Plan.tla. For the two specs that agreement was maintained by hand, by
someone remembering -- and `drift` has reported the resulting mismatch more
than once.

This removes the class rather than checking for it. The numbers are read
out of blob.h and written into a generated Alloy module and a generated TLC
config, so the specs cannot hold a stale copy: there is no second
declaration left to drift.

Writes (both generated, both gitignored):
    specs/limits.als    -- opened by plan.als
    specs/Plan.cfg      -- the TLC config for Plan.tla

Not in the TCB. Run by tests/run.py before it invokes the solvers.
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The names the specs need, and what each is called in blob.h. Anything the
# specs reason about numerically belongs here; anything they do not, does
# not, because a constant nothing reads is a constant that rots.
WANTED = {
    "nwMaxUnits": "NW_MAX_UNITS",
    "nwMaxFds": "NW_MAX_FDS",
    "nwReserved": "NW_FD_RESERVED",
    "nwMaxBinds": "NW_MAX_BINDS",
}


def read_blob_h(path=None):
    src = open(path or os.path.join(ROOT, "blob.h")).read()
    out = {}
    for spec_name, c_name in WANTED.items():
        # `(\d+)` alone reads 0x8 as 0 and 0200 as 200, silently, and
        # re.search takes the FIRST #define so an #ifdef pair hands back
        # whichever arm is written first. `control` put
        # `#define NW_FD_RESERVED 0x8` in blob.h -- identical to the C
        # preprocessor, every _Static_assert intact -- and both specs
        # then reasoned with Reserved = 0 and both passed, because
        # FdArithmetic uses it on both sides and FdBudgetCovers only got
        # slacker. Removing the second copy does not help if the first
        # one is read wrong.
        pat = rf"^[ \t]*#[ \t]*define[ \t]+{c_name}[ \t]+(\S+)[ \t]*$"
        found = re.findall(pat, src, re.M)
        if not found:
            raise SystemExit(
                f"gen-spec-limits: {c_name} not found in blob.h as a plain "
                f"single-line #define. The specs derive their limits from "
                f"it; a rename or a computed value here is a four-place "
                f"change (invariant 3) and must not be papered over with a "
                f"default.")
        if len(found) > 1:
            raise SystemExit(
                f"gen-spec-limits: {c_name} is defined {len(found)} times "
                f"in blob.h ({found}). Which one the compiler uses depends "
                f"on #if arms this tool cannot see, so it refuses to guess.")
        tok = found[0]
        try:
            # base 0: honours 0x.. and 0.. exactly as C does.
            val = int(tok, 0)
        except ValueError:
            raise SystemExit(
                f"gen-spec-limits: {c_name} is `{tok}`, which is not an "
                f"integer literal this tool can read. Spell it as one, or "
                f"teach this tool to run cpp -- do not let it guess.")
        if val < 0:
            raise SystemExit(f"gen-spec-limits: {c_name} is negative")
        out[spec_name] = val
    return out


def als(vals):
    body = "\n".join(
        f"fun {k}[]: Int {{ {v} }}" for k, v in sorted(vals.items()))
    return f"""/* GENERATED by tools/gen-spec-limits.py from blob.h. Do not edit.
   Regenerate rather than correcting this file: it exists so plan.als
   cannot hold a second, drifting copy of a limit (invariant 3). */
module limits

{body}
"""


def cfg(vals):
    return f"""\\* GENERATED by tools/gen-spec-limits.py from blob.h. Do not edit.
\\* Plan.tla's ASSUME compares these against the values it was written
\\* with; a blob.h change that Plan.tla has not followed fails the ASSUME,
\\* which is the drift invariant 3 exists to catch.
CONSTANTS
    MaxUnits = {vals['nwMaxUnits']}
    MaxFds = {vals['nwMaxFds']}
    Reserved = {vals['nwReserved']}
    MaxBinds = {vals['nwMaxBinds']}

INIT Init
NEXT Next

INVARIANTS
    FdBudgetCovers
    FdNeedAgrees
    LargestCityFits
    TypeOK
"""


def generate(out_dir=None, blob_h=None):
    vals = read_blob_h(blob_h)
    d = out_dir or os.path.join(ROOT, "specs")
    os.makedirs(d, exist_ok=True)
    a, c = os.path.join(d, "limits.als"), os.path.join(d, "Plan.cfg")
    open(a, "w").write(als(vals))
    open(c, "w").write(cfg(vals))
    return vals, a, c


if __name__ == "__main__":
    v, a, c = generate()
    print(f"gen-spec-limits: {v}")
    print(f"  {a}")
    print(f"  {c}")
    sys.exit(0)
